# Generated by Django 5.0.6 on 2024-07-09 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_organisation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='user',
            field=models.ManyToManyField(related_name='organisations', to=settings.AUTH_USER_MODEL),
        ),
    ]
