# Generated by Django 5.0.6 on 2024-07-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ogranisation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ogranisation',
            new_name='Organisation',
        ),
    ]
